# Generated by Django 2.2.1 on 2019-09-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20190917_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='selected_q',
            new_name='sel_ques',
        ),
    ]
